## 本地IB软件包目录，请勿删除
src imagebuilder file:packages

## rockchip armv8 平台核心包
src/gz openwrt_core https://archive.openwrt.org/releases/25.12.4/targets/rockchip/armv8/packages

## aarch64_cortex-a53 通用软件源
src/gz openwrt_base https://archive.openwrt.org/releases/25.12.4/packages/aarch64_cortex-a53/base
src/gz openwrt_luci https://archive.openwrt.org/releases/25.12.4/packages/aarch64_cortex-a53/luci
src/gz openwrt_packages https://archive.openwrt.org/releases/25.12.4/packages/aarch64_cortex-a53/packages
src/gz openwrt_routing https://archive.openwrt.org/releases/25.12.4/packages/aarch64_cortex-a53/routing
src/gz openwrt_telephony https://archive.openwrt.org/releases/25.12.4/packages/aarch64_cortex-a53/telephony

# 第三方插件源（PassWall2按需启用）
# src/gz passwall https://opkg.immortalwrt.org/releases/packages-25.12/aarch64_cortex-a53/passwall

# 关闭签名校验
option check_signature 0
