# dllkids第三方源置顶（优先加载OpenClash、Lucky）
src/gz dllkids https://down.dllkids.xyz/openwrt-feed/25.12/aarch64_cortex-a53

# 本地离线包目录（不可删除）
src imagebuilder file:packages

# OpenWrt 25.12.1 官方原生源 rockchip armv8
src/gz openwrt_core https://archive.openwrt.org/releases/25.12.1/targets/rockchip/armv8/packages
src/gz openwrt_base https://archive.openwrt.org/releases/25.12.1/packages/aarch64_cortex-a53/base
src/gz openwrt_luci https://archive.openwrt.org/releases/25.12.1/packages/aarch64_cortex-a53/luci
src/gz openwrt_packages https://archive.openwrt.org/releases/25.12.1/packages/aarch64_cortex-a53/packages
src/gz openwrt_routing https://archive.openwrt.org/releases/25.12.1/packages/aarch64_cortex-a53/routing
src/gz openwrt_telephony https://archive.openwrt.org/releases/25.12.1/packages/aarch64_cortex-a53/telephony

# 关闭签名校验，第三方ip免密钥
option check_signature 0
